###GET(Traer una orden en particular)
GET http://localhost:8000/api/order/625f07ffdba54c7a4e65a7aa
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTcyNGFjNjYwNDEwNDA1NTdmMDI2YSIsImlhdCI6MTY1MDM5MzgwNSwiZXhwIjoxNjUyOTg1ODA1fQ.eOjY__v6v2ppzMaoq4XJL6XoNuKme4olvP4cETEewOE

###GET(Traer todas las ordenes del usuario)
GET http://localhost:8000/api/order/myorders
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTcyNGFjNjYwNDEwNDA1NTdmMDI2YSIsImlhdCI6MTY1MDM5MzgwNSwiZXhwIjoxNjUyOTg1ODA1fQ.eOjY__v6v2ppzMaoq4XJL6XoNuKme4olvP4cETEewOE

