### Buscar todos los productos
GET http://localhost:8000/api/products

### Buscar un solo producto
GET http://localhost:8000/api/product/6197f36dbb1109d55be21a58


###
POST http://localhost:8000/api/login
Content-Type: application/json


{
  "email":"tefita@example.com",
  "password":"123456aea"
}

###ADMIN LOGIN
POST http://localhost:8000/api/login
Content-Type: application/json


{
  "email":"admin@example.com",
  "password":"123456aea"
}



###GET COMMON USER PROFILE
GET http://localhost:8000/api/profile
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTdmMzZkYmIxMTA5ZDU1YmUyMWE1NSIsImlhdCI6MTY0MjI1OTE0MSwiZXhwIjoxNjQ3NDQzMTQxfQ.HiL-9Gn_rhx-jBlCuMlTaAdK_8ubwK5x1FzvcaD9vkM

###GET USER PROFILE
GET http://localhost:8000/api/profile
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTdmMzZkYmIxMTA5ZDU1YmUyMWE1NCIsImlhdCI6MTY0MjI2Mjc5MiwiZXhwIjoxNjQ3NDQ2NzkyfQ.U7j8ksAr7laQy4ji8AUDw13slj5vO1VFSyom3e_qBoM
