### GET USERS

GET http://localhost:8000/api/users


### REGISTER
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "name":"papo",
  "email":"papo@example.com",
  "password":"argentina4567"
}



### USER LOGIN
POST http://localhost:8000/api/login
Content-Type: application/json


{
  "email":"papo@example.com",
  "password":"argentina4567"
}

###ADMIN LOGIN
POST http://localhost:8000/api/login
Content-Type: application/json


{
  "email":"admin@example.com",
  "password":"123456aea"
}



###GET COMMON USER PROFILE
GET http://localhost:8000/api/profile
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTdmMzZkYmIxMTA5ZDU1YmUyMWE1NiIsImlhdCI6MTY0MjI2NDAyMywiZXhwIjoxNjQ0ODU2MDIzfQ.H02bQ_PrgFoT_rjS_4RCNmW3o_YQTyzNslxSUISWZxA


###GET USER PROFILE
GET http://localhost:8000/api/profile
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTdmMzZkYmIxMTA5ZDU1YmUyMWE1NCIsImlhdCI6MTY0MjI2Mjc5MiwiZXhwIjoxNjQ3NDQ2NzkyfQ.U7j8ksAr7laQy4ji8AUDw13slj5vO1VFSyom3e_qBoM

###PUT USER Profile

PUT http://localhost:8000/api/updateProfile/61e30c1581f1572f13a14a20
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTdmMzZkYmIxMTA5ZDU1YmUyMWE1NCIsImlhdCI6MTY0MjI2Mjc5MiwiZXhwIjoxNjQ3NDQ2NzkyfQ.U7j8ksAr7laQy4ji8AUDw13slj5vO1VFSyom3e_qBoM

{
  "name":"Walls",
  "email":"walls@example.com",
  "password":"spain45678"
}