### GET USERS

GET http://localhost:8000/api/users
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzhkZjA0MzA5Y2EwNGU0NDRlYzcwZSIsImlhdCI6MTY0ODQ5NTY5MSwiZXhwIjoxNjUxMDg3NjkxfQ.k8n0twjp_cxJlmI_mG4ZO6mMX1EMWmQvg_eRo4bjC7w


### GET SINGLE USER

GET http://localhost:8000/api/user/6239f3edfb476dc092698255
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTdmMzZkYmIxMTA5ZDU1YmUyMWE1NiIsImlhdCI6MTY0MjI2NDAyMywiZXhwIjoxNjQ0ODU2MDIzfQ.H02bQ_PrgFoT_rjS_4RCNmW3o_YQTyzNslxSUISWZxA


### REGISTER
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "name":"papo",
  "email":"papo@example.com",
  "password":"argentina4567"
}



### USER LOGIN
POST http://localhost:8000/api/login
Content-Type: application/json


{
  "email":"admin@example.com",
  "password":"123456"
}

###ADMIN LOGIN
POST http://localhost:8000/api/login
Content-Type: application/json


{
  "email":"admin@example.com",
  "password":"123456aea"
}



###GET USER PROFILE
GET http://localhost:8000/api/profile
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzllYmQ0MDBhZDFjZGM0NTZlZjhlZCIsImlhdCI6MTY0Nzk2OTI5OSwiZXhwIjoxNjUwNTYxMjk5fQ.Pcz29bLLoGTwqHvZZpa4fuxJbHiDCHnlnwxApwuj5Qc

###PUT USER Profile

PUT http://localhost:8000/api/updateProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTdmMzZkYmIxMTA5ZDU1YmUyMWE1NCIsImlhdCI6MTY0MjI2Mjc5MiwiZXhwIjoxNjQ3NDQ2NzkyfQ.U7j8ksAr7laQy4ji8AUDw13slj5vO1VFSyom3e_qBoM

{
  "name":"Walls",
  "email":"walls@example.com",
  "password":"spain45678"
}